- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - homebrew
    - homebrew-cask
    - ruby-build
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
      - sanemat/font

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - readline
      - redis
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - ansible
      - docker
      - git
      - git-flow
      - heroku-toolbelt
      - imagemagick
      - libxml2
      - peco
      - phantomjs
      #- mysql
      - homebrew/versions/mysql56
      - nvm
      - rbenv
      - ruby-build
      - the_silver_searcher
      #- vim
      - yarn
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
      - adobe-creative-cloud
      - clipy
      - coteditor
      - cyberduck
      - docker
      - dropbox
      - firefox
      - google-chrome
      - google-drive-file-stream
      - google-japanese-ime
      - gyazo
      - imageoptim
      - java6
      - karabiner-elements
      #- cmd-eikana
      - mamp
      - sequel-pro
      - sketch
      - sketch-toolbox
      - skitch
      - slack
      - sublime-text
      - sourcetree
      - 1password
